repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check Backend with Flake8
        files: ^backend/
        types: [python]
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

    #  - repo: https://github.com/pre-commit/mirrors-eslint
    #    rev: v9.10.0
    #    hooks:
    #      - id: eslint
    #        files: \.(js|ts|jsx|tsx)$
    #        additional_dependencies:
    #          - eslint@9.10.0
    #          - globals@15.0.0
