repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check Backend with Flake8
        files: ^backend/
        types: [python]
        additional_dependencies: [flake8-bugbear, flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
      - id: eslint
        name: Check Frontend with ESLint
        files: ^frontend/
        types: [file]
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - eslint@8.40.0
          - eslint-config-react-app@7.0.1

  - repo: local
    hooks:
      - id: poetry-check
        name: Poetry check
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true
      - id: poetry-lock-check
        name: Poetry lock check
        entry: poetry lock --check
        language: system
        pass_filenames: false
        files: pyproject.toml

      # New local hook to run pytest
      - id: pytest
        name: Run Pytest for Backend
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        files: ^backend/

      # New local hook to run npm test
      - id: npm-test
        name: Run npm test for Frontend
        entry: cd frontend && npm test -- --watchAll=false
        language: system
        pass_filenames: false
        always_run: true
